// Methods
import '../../api/methods/errors';
import '../../api/methods/security';
import '../../api/methods/pushNotification';
import '../../api/methods/login';
import '../../api/methods/business';
import '../../api/methods/store';
import '../../api/methods/staff';
import '../../api/methods/account';
import '../../api/methods/notifications';
import '../../api/methods/systemMessages';
import '../../api/methods/promotions';